# Site settings
url: "http://www.learnwebservices.com"

# URL of the backend server
api_url: "http://www.learnwebservices.com"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge